# Generated by Django 3.0.5 on 2020-06-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_auto_20200526_1315"),
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roster",
            name="players",
            field=models.ManyToManyField(blank=True, to="players.Player"),
        ),
    ]
