# Generated by Django 3.0.5 on 2020-06-08 15:46

import autoslug.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import sghymnal.foes.models
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('squad_number', models.IntegerField(default=0)),
                ('position', models.CharField(blank=True, choices=[('Forward', 'Forward'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Goalkeeper', 'Goalkeeper'), ('Head Coach', 'Head Coach'), ('Assistant Coach', 'Assistant Coach'), ('Goalkeeper Coach', 'Goalkeeper Coach'), ('Technical Director', 'Technical Director'), ('Associate Head Coach', 'Associate Head Coach')], max_length=50, verbose_name='Position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opponent', models.CharField(max_length=255, verbose_name='Opponent Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='opponent', unique=True, verbose_name='Foe Slug')),
                ('competition', models.CharField(blank=True, max_length=255, verbose_name='Competition')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, upload_to=sghymnal.foes.models.foe_upload_path, verbose_name='Foe Logo')),
                ('background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Background Color')),
                ('accent_color', colorfield.fields.ColorField(default='#FFFF00', max_length=18, verbose_name='Accent Color')),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Text Color')),
                ('season', models.CharField(max_length=255, verbose_name='Season')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foe', to='foes.FoePlayer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
