# Generated by Django 3.0.5 on 2020-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foe',
            name='players',
        ),
        migrations.AddField(
            model_name='foeplayer',
            name='foe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='foes.Foe'),
            preserve_default=False,
        ),
    ]
