# Generated by Django 3.0.5 on 2020-06-11 19:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import sghymnal.songbooks.models
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0002_auto_20200610_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Songbook Slug')),
                ('orginization', models.CharField(blank=True, max_length=255, verbose_name='Orginization')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('front_cover', sorl.thumbnail.fields.ImageField(blank=True, upload_to=sghymnal.songbooks.models.songbook_front_cover_upload_path, verbose_name='Front Cover')),
                ('back_cover', sorl.thumbnail.fields.ImageField(blank=True, upload_to=sghymnal.songbooks.models.songbook_back_cover_upload_path, verbose_name='Back Cover')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('songbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='songbooks.Songbook')),
                ('songs', models.ManyToManyField(to='songs.Song')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
