# Generated by Django 3.0.5 on 2020-06-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songbook',
            name='orginization',
        ),
        migrations.AddField(
            model_name='songbook',
            name='organization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Organization'),
        ),
    ]
