# Generated by Django 3.0.5 on 2020-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Players Number'),
        ),
    ]
