# Generated by Django 3.0.5 on 2020-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_auto_20200526_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="squad_number",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Players Number"
            ),
        ),
    ]
